"""Interrogate route"""
from fastapi import APIRouter, HTTPException

from app.api.database.models import InterrogateRequest, InterrogateResponse
from app.api.helpers.utils import decode_base64_to_image
from app.logger.logger import configure_logging
from app.ml.modules import shared

# to get a string like this run:
# openssl rand -hex 32

logger = configure_logging(__name__)
router = APIRouter()


@router.post("/", response_model=InterrogateResponse)
async def interrogateapi(interrogatereq: InterrogateRequest):
    """
    This function takes an image and a model type as input, processes the image using the specified
    model, and returns the processed result as a caption.
    
    :param interrogatereq: InterrogateRequest is a data model that contains the necessary information
    for the API to process an image and return a caption. It includes an image in base64 format and the
    name of the model to use for processing the image
    :type interrogatereq: InterrogateRequest
    :return: an instance of the `InterrogateResponse` class, which contains the processed caption
    generated by the `shared.interrogator.interrogate` method.
    """
    image_b64 = interrogatereq.image
    if image_b64 is None:
        raise HTTPException(status_code=404, detail="Image not found")

    img = decode_base64_to_image(image_b64)
    img = img.convert('RGB')

    if interrogatereq.model == "clip":
        processed = shared.interrogator.interrogate(img)
    else:
        raise HTTPException(status_code=404, detail="Model not found")

    return InterrogateResponse(caption=processed)
